@startuml
!include <tupadr3/common>

!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Concepts/firewall_orange>
!include <office/Clouds/cloud_disaster_red>
!include <office/Devices/cell_phone_iphone_proportional>
!include <office/Concepts/service_application>
!include <office/Concepts/application_web>
!include <office/Servers/web_server>
!include <tupadr3/material/phone_iphone>

title Office Icons Example

package "Sprites" {
    OFF_DATABASE_SERVER(db,DB)
    OFF_APPLICATION_SERVER(app,App-Server)
    OFF_FIREWALL_ORANGE(fw,Firewall)
    OFF_CLOUD_DISASTER_RED(cloud,Cloud)

    db <-> app
    app <--> fw
    fw <.left.> cloud
}


OFF_CELL_PHONE_IPHONE_PROPORTIONAL(iphone,Applicant)
OFF_SERVICE_APPLICATION(nextGen,Next Gen)
OFF_WEB_SERVER(web_server,Web-Server)
OFF_APPLICATION_WEB(web,TU(TransUnion))
MATERIAL_PHONE_IPHONE(iphone2,iPhone, rectangle, green)

@enduml
